name: Deploy to EC2 with appleboy/ssh-action

on:
  workflow_call: # Allows manual triggering of the workflow from the GitHub Actions tab


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create folder
        uses: appleboy/ssh-action@v1.0.3 # Use SSH action for executing commands
        with:
          host: ${{ secrets.EC2.SSH_HOST }}
          username: ${{ secrets.EC2.SSH_USERNAME }}
          key: ${{ secrets.EC2.SSH_PRIVATE_KEY }}
          script: |
            echo "Creating directory if it doesn't exist..."
            sudo apt-get update && sudo apt-get install -y docker.io docker-compose
            sudo usermod -aG docker $USER
            mkdir -p ~/devops

      - name: Copy files via scp
        uses: appleboy/scp-action@v0.1.3 # Use the latest stable version
        with:
          host: ${{ secrets.EC2.SSH_HOST }}
          username: ${{ secrets.EC2.SSH_USERNAME }}
          key: ${{ secrets.EC2.SSH_PRIVATE_KEY }}
          source: docker-compose.yml # Local files/directories to transfer
          target: ~/devops

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.3 # Use the latest version
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
          
            docker pull faiz1575/github-actions-app:latest
            docker stop app || true
            docker rm app || true
            docker run -d -p 80:80 --name app ${{ vars.DOCKERHUB_USER }}/github-actions-app:${{ github.sha}}
            # Enter the commands you want to run on your EC2 instance
            cd /var/www/your-app
            git pull origin main
            # Example: restart a service or run a build command
            # sudo systemctl restart your-service
            echo "Deployment completed successfully!"
