name: secret scan
# we are using gitleaks to scan for secrets in our codebase. gitleaks is a popular open-source tool for scanning git repositories for secrets. It can detect a wide range of secrets, including API keys, passwords, and other sensitive information.

on: 
  workflow_call:

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          #fetch-depth: 0 is required to scan the entire git history for secrets.
          # If you only fetch the latest commit, you will miss any secrets that were committed in the past and then removed.

      - name: gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      